WIP. Fix for simple-fmt dependency error.
Not sure why, but npm install is not picking up ng-annotate's simple-fmt
lib dep.
This is what I see in CI:
```sh
Error: Cannot find module 'simple-fmt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (---REDACTED---/gulp/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm ERR! not ok code 0
```

Need a solution that will allow me to
```sh
$ npm i
```
without erroring.

- package.json  Locked the simple-fmt dependency down to specific
  version.